---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: postgres-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scc-postgres
subjects:
- kind: ServiceAccount
  name: postgres-sq
  namespace: rhel-lightspeed
